#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'
ENV["MIGRATOR_CALLER"] = "console"
libs = " -r #{File.dirname(__FILE__) + '/../lib/cachebag'} -r ruby-debug"
puts "Loading gem development environment..."
exec "#{irb} #{libs} --simple-prompt #{ARGV.join("")}"
